In [1]:
import numpy as np
from scipy import linalg as la

In [2]:
A=np.array([[1,5,2],[2,4,1],[3,6,2]])

In [3]:
lna,v=la.eig(A)

In [5]:
l1,l2,l3=lna

In [6]:
print(l1,l2,l3)

(7.95791620491+0j) (-1.25766470568+0j) (0.299748500767+0j)


In [7]:
print(v)

[[-0.5297175  -0.90730751  0.28380519]
 [-0.44941741  0.28662547 -0.39012063]
 [-0.71932146  0.30763439  0.87593408]]


In [8]:
print(v[:,0])   # 所有列第 0行

[-0.5297175  -0.44941741 -0.71932146]


In [9]:
print(v[:,1])   # 所有列第 1行

[-0.90730751  0.28662547  0.30763439]


In [10]:
print(v[:,2])   # 所有列第 2行

[ 0.28380519 -0.39012063  0.87593408]


In [11]:
v1=np.array(v[:,0]).T    # 轉置矩陣

In [12]:
print(v1)

[-0.5297175  -0.44941741 -0.71932146]


In [13]:
print(la.norm(A.dot(v1)-l1*v1))    # norm 顯示值

3.233018248352212e-15
