In [1]:
import numpy as np
from scipy import linalg   # 線性代數的函式庫

In [3]:
A=np.array([[1,3,5],[2,5,1],[2,3,8]])
print(A)

[[1 3 5]
 [2 5 1]
 [2 3 8]]


In [4]:
print(linalg.inv(A))      # inv 矩陣的反函數

[[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]


In [5]:
print(A.dot(linalg.inv(A)))   # 和反矩陣做內積

[[  1.00000000e+00  -1.11022302e-16  -6.24500451e-17]
 [  3.05311332e-16   1.00000000e+00   1.87350135e-16]
 [  2.22044605e-16  -1.11022302e-16   1.00000000e+00]]
