In [28]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp
import IPython
import sklearn
import mglearn
# import pandas.plotting

In [16]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

print("Key of iris_dataset: \n{}".format(iris_dataset.keys()))

Key of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [2]:
# show the type

print(iris_dataset['DESCR'][:193] + "\n...")
print("==================")
print("Target names: {}".format(iris_dataset['target_names']))   # string array
print("==================")
print("Feature names: \n{}".format(iris_dataset['feature_names']))  # string
print("==================")
print("Type of data: {}".format(type(iris_dataset['data'])))     # class

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...
Target names: ['setosa' 'versicolor' 'virginica']
Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Type of data: <class 'numpy.ndarray'>


In [6]:
print("Shape of data: {}".format(iris_dataset['data'].shape))    # (幾種花 simples, 特徵 features)
print("==================")
print("First five column of data:\n{}".format(iris_dataset['data'][:5]))  # 前五個樣本的特徵值
print("==================")
print("Type of target: {}".format(type(iris_dataset['target'])))    # Numpy array

Shape of data: (150, 4)
First five column of data:
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
Type of target: <class 'numpy.ndarray'>


In [9]:
print("Shape of target: {}".format(iris_dataset['target'].shape))   # Species is make up of 0 to 2
print("==================")
print("Target:\n{}".format(iris_dataset['target']))    # 0 is setosa, 1 is versicolor, 2 is virginica

Shape of target: (150,)
Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
# use the train_test_split to process data
import pandas as pd
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

In [11]:
# X_train 75%, X_test data only have 25%
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


In [31]:
# 查看資料
# 用 X_train 資料建立 dataframe
# 用 iris_dataset.feature_names 的字串值當作標籤欄位
from pandas.plotting import scatter_matrix
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
# 從 dataframe 建立點陣矩陣，顏色是依據 y_train 這個值
grr = pd.scatter_matrix(iris_dataframe, c=y_train, figsize=(15,15), marker='o', 
                        hist_kwds={'bins': 20}, s=60, alpha=.8, cmap=mglearn.cm3)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: pandas.scatter_matrix is deprecated. Use pandas.plotting.scatter_matrix instead
  


In [32]:
'''
建立 KNN
'''
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
print(knn.fit(X_train, y_train))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [36]:
# 做預測
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape)).  # (simples, features)

X_new.shape: (1, 4)


In [39]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
            iris_dataset['target_names'][prediction]))    # 預測為 setosa 花種

Prediction: [0]
Predicted target name: ['setosa']


In [40]:
# 評估模組，計算準確度(accuracy)
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [41]:
print("Test set score: {:.2f}".format(np.mean(y_pred == y_test)))

Test set score: 0.97


In [42]:
print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))   # 使用 score，結果同上

Test set score: 0.97


In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

print("Test set score: {:.2f}".format(knn.score(X_test, y_test)))   # fit states

Test set score: 0.97
